add oidc to output
volodymyrilov/terraform-aws-eks pull request #2
Opened 2020-06-22 13:38 UTC by denys1yermakov

for assign roles to SA

2020-06-22 14:49 UTC, oleksandr-shkovyra requested changes

2020-06-22 14:49 UTC, cfifua commented on irsa.tf
> +data "aws_eks_cluster" "example" {
"example" - is not the best name for the resource, considering changing it.

2020-06-22 14:49 UTC, cfifua commented on variables.tf
> +  default     = "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
where do we take this value?

2020-06-23 08:40 UTC, denys1yermakov commented on variables.tf
> +  default     = "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
provided by aws

2020-06-23 08:43 UTC, oleksandr-shkovyra approved these changes

2020-06-23 08:43 UTC, merged